# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create and change to the app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the TypeScript code (if needed)
RUN npm run build

# Expose port if the server listens on a port (assumed not needed for MCP server over stdio)

# Start the server
CMD [ "npm", "start" ]
